class Demo
{
	/*public static void main(String args[])
	{
		int c=84, py=75, java=95, total=300;
		double all=c+py+java;
		double percentage=all/total*100;
		System.out.println(percentage);
	}
	public static void main(String args[])
	{
		String name="Inthiyaz";
		char code='i';
		int price=55;
		int quantity=5;
		double total=(price*quantity)/100;
		double discount=total/100*5;
		double final =total-discount;
		System.out.println(final);
	}
	public static void main(String args[])
	{
		double x=8.0;
		boolean b;
		float age=10.5f;
		System.out.println(b);
	}
	public static void main(String args[])
	{
		int math=25, sci=30, social=20;
		double total_marks=90;
		int add=math+sci+social;
		double per=add/total_marks*100;
		System.out.println(per);
	}*/
	public static void main(String args[])
	{
		int a=(int)7.5;
		System.out.println(a);
	}
}